document.documentElement.classList.add('js');
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(e=>observer.observe(e));
const menu=document.querySelector('#menu'),nav=document.querySelector('#navigation');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}));
const areas={west:{label:'WHERE OUR JOURNEY BEGAN',title:'The Western Suburbs',copy:'Our foundation and primary market. Local experience across the Western belt helps us guide conversations about neighbourhoods, residential projects, and your daily life.',places:['Bandra','Goregaon','Borivali','Dahisar']},central:{label:'A WIDER MUMBAI PERSPECTIVE',title:'Central & South Mumbai',copy:'Our advisory footprint extends beyond the Western belt. Explore established neighbourhoods and residential opportunities with guidance tailored to your plans.',places:['Central Mumbai','South Mumbai','Dadar']},extended:{label:'OUR EXPANDING FOCUS',title:'Beyond the city limits',copy:'We are expanding our focus across the surrounding suburbs. Contact us to discuss your location and the opportunities we can help you explore.',places:['Thane','Mira-Bhayandar','Kalyan','Navi Mumbai','Vasai-Virar']}};
const tabs=[...document.querySelectorAll('[role=tab]')];function selectTab(tab){tabs.forEach(t=>{t.setAttribute('aria-selected',String(t===tab));t.tabIndex=t===tab?0:-1});const area=areas[tab.dataset.area];document.querySelector('#area-label').textContent=area.label;document.querySelector('#area-title').textContent=area.title;document.querySelector('#area-copy').textContent=area.copy;document.querySelector('#locations').replaceChildren(...area.places.map(p=>{const s=document.createElement('span');s.textContent=p;return s}));const panel=document.querySelector('#area-panel');panel.setAttribute('aria-labelledby',tab.id);panel.classList.remove('changed');requestAnimationFrame(()=>panel.classList.add('changed'))}tabs.forEach((tab,i)=>{tab.addEventListener('click',()=>selectTab(tab));tab.addEventListener('keydown',event=>{let n;if(['ArrowDown','ArrowRight'].includes(event.key))n=(i+1)%tabs.length;else if(['ArrowUp','ArrowLeft'].includes(event.key))n=(i+tabs.length-1)%tabs.length;else if(event.key==='Home')n=0;else if(event.key==='End')n=tabs.length-1;else return;event.preventDefault();tabs[n].focus();selectTab(tabs[n])})});
document.querySelector('#enquiry').addEventListener('submit',event=>{event.preventDefault();const f=event.currentTarget;if(!f.reportValidity())return;const data=new FormData(f);const message=['Hello Blue Home Realty,','My name is '+data.get('name')+'.','Interested in: '+data.get('interest'),'Preferred location: '+data.get('location'),data.get('message')||'','Please help me explore the next step.'].filter(Boolean).join('\n');const link=document.createElement('a');link.href='https://wa.me/919152054551?text='+encodeURIComponent(message);link.target='_blank';link.rel='noopener noreferrer';link.className='text-link';link.textContent='Open WhatsApp to review and send';document.querySelector('#form-status').replaceChildren(document.createTextNode('Your message is ready. '),link);link.click()});document.querySelector('#year').textContent=new Date().getFullYear();

// Service explorer: one clear choice and preview, with native keyboard buttons.
const serviceButtons=[...document.querySelectorAll('.service-toggle')];
serviceButtons.forEach(button=>button.addEventListener('click',()=>{
  serviceButtons.forEach(other=>{const selected=other===button;other.setAttribute('aria-expanded',String(selected));other.closest('.service-choice').classList.toggle('active',selected);document.getElementById(other.getAttribute('aria-controls')).hidden=!selected;});
  const stage=document.querySelector('.service-stage'),image=document.querySelector('#service-image');image.src=button.dataset.photo;image.alt=button.querySelector('span:nth-child(2)').textContent+' — presentation imagery';document.querySelector('#service-counter').textContent=button.dataset.number+' / 04';stage.classList.remove('swapping');requestAnimationFrame(()=>stage.classList.add('swapping'));
}));
const reduceMotion=matchMedia('(prefers-reduced-motion: reduce)');let scrollScheduled=false;
function paintScroll(){const y=window.scrollY,range=document.documentElement.scrollHeight-window.innerHeight;document.querySelector('.reading-progress').style.transform='scaleX('+(range>0?Math.min(1,y/range):0)+')';if(!reduceMotion.matches)document.querySelector('.hero-photograph').style.setProperty('--hero-shift',Math.min(y*.12,90)+'px');scrollScheduled=false;}
addEventListener('scroll',()=>{if(!scrollScheduled){scrollScheduled=true;requestAnimationFrame(paintScroll)}},{passive:true});paintScroll();
